name: Build and Upload Binary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-dev \
            libcairo2-dev \
            libglib2.0-dev \
            libcurl4-openssl-dev \
            build-essential \
            cmake \
            pkg-config

      - name: Build project
        run: |
          chmod +x ./build.sh &&
          ./build.sh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ElysiaDownloader
          path: |
            build/ElysiaDownloader
